#!/usr/bin/env bash
#
#  rubd The Rub Core server.
#
#
# chkconfig: 345 80 20
# description: rubd
# processname: rubd
#

# Source function library.
. /etc/init.d/functions

# you can override defaults in /etc/sysconfig/rubd, see below
if [ -f /etc/sysconfig/rubd ]; then
        . /etc/sysconfig/rubd
fi

RETVAL=0

prog=rubd
# you can override the lockfile via BITCOIND_LOCKFILE in /etc/sysconfig/rubd
lockfile=${BITCOIND_LOCKFILE-/var/lock/subsys/rubd}

# rubd defaults to /usr/bin/rubd, override with BITCOIND_BIN
rubd=${BITCOIND_BIN-/usr/bin/rubd}

# rubd opts default to -disablewallet, override with BITCOIND_OPTS
rubd_opts=${BITCOIND_OPTS--disablewallet}

start() {
    echo -n $"Starting $prog: "
    daemon $DAEMONOPTS $rubd $rubd_opts
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch $lockfile
    return $RETVAL
}

stop() {
    echo -n $"Stopping $prog: "
    killproc $prog -t600
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && rm -f $lockfile
    return $RETVAL
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status $prog
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: service $prog {start|stop|status|restart}"
        exit 1
        ;;
esac
